# Site settings
title: "A Journey in Tech - Pedro Kaetsu"
email: "phksardeto@gmail.com"
url: https://pedrokaetsu.github.io
description: "Personal Site"
github_username: "PedroKaetsu"
markdown: GFM
